apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: prod
spec:
  type: NodePort
  selector:
    name: todo-app
  ports:
    - name: todo-app
      port: 8080
      targetPort: 8080
      nodePort: 30080