apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Deepak-Kumar07/todoApp.git
    targetRevision: main
    path: kubernetes/todoApp
  destination:
    server: https://kubernetes.default.svc
    namespace: prod