apiVersion: v1
kind: Service
metadata:
  name: todo-db-service
  namespace: prod
spec:
  selector:
    name: todo-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
