apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db
  namespace: prod
spec:
  selector:
    matchLabels:
      name: todo-db
  replicas: 1
  template:
    metadata:
      labels:
        name: todo-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-data
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-data
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-data
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-data
                  key: MYSQL_PASSWORD
          resources:
            requests:
              memory: 1.5Gi
            limits:
              memory: 2Gi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "mysqladmin ping -h 127.0.0.1 -u $MYSQL_USER -p$MYSQL_PASSWORD"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
              # subPath: init.sql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-claim
        - name: mysql-init
          configMap:
            name: db-config
